// This program is copyright 2019-2026 Percona LLC and/or its affiliates.
//
// THIS PROGRAM IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
// WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
//
// This program is free software; you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, version 2.
//
// You should have received a copy of the GNU General Public License, version 2
// along with this program; if not, see <https://www.gnu.org/licenses/>.

// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// AllDatabases represents a row from '[custom all_databases]'.
type AllDatabases struct {
	Datname Name // datname
}

// GetAllDatabases runs a custom query, returning results as AllDatabases.
func GetAllDatabases(db XODB) ([]*AllDatabases, error) {
	var err error

	// sql query
	sqlstr := `SELECT datname ` +
		`FROM pg_database ` +
		`WHERE datistemplate = false`

	// run query
	XOLog(sqlstr)
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*AllDatabases{}
	for q.Next() {
		ad := AllDatabases{}

		// scan
		err = q.Scan(&ad.Datname)
		if err != nil {
			return nil, err
		}

		res = append(res, &ad)
	}

	return res, nil
}
