// This program is copyright 2019-2026 Percona LLC and/or its affiliates.
//
// THIS PROGRAM IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
// WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
//
// This program is free software; you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, version 2.
//
// You should have received a copy of the GNU General Public License, version 2
// along with this program; if not, see <https://www.gnu.org/licenses/>.

// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// Connections represents a row from '[custom connections]'.
type Connections struct {
	State string // state
	Count int64  // count
}

// GetConnections runs a custom query, returning results as Connections.
func GetConnections(db XODB) ([]*Connections, error) {
	var err error

	// sql query
	sqlstr := `SELECT state, count(*) ` +
		`FROM pg_stat_activity ` +
		`GROUP BY 1`

	// run query
	XOLog(sqlstr)
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*Connections{}
	for q.Next() {
		c := Connections{}

		// scan
		err = q.Scan(&c.State, &c.Count)
		if err != nil {
			return nil, err
		}

		res = append(res, &c)
	}

	return res, nil
}
