// This program is copyright 2019-2026 Percona LLC and/or its affiliates.
//
// THIS PROGRAM IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
// WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
//
// This program is free software; you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, version 2.
//
// You should have received a copy of the GNU General Public License, version 2
// along with this program; if not, see <https://www.gnu.org/licenses/>.

// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// GlobalWaitEvents represents a row from '[custom global_wait_events]'.
type GlobalWaitEvents struct {
	WaitEventType string // wait_event_type
	WaitEvent     string // wait_event
	Count         int64  // count
}

// GetGlobalWaitEvents runs a custom query, returning results as GlobalWaitEvents.
func GetGlobalWaitEvents(db XODB) ([]*GlobalWaitEvents, error) {
	var err error

	// sql query
	const sqlstr = `SELECT wait_event_type, wait_event, count(*) ` +
		`FROM pg_stat_activity ` +
		`WHERE wait_event_type IS NOT NULL ` +
		`OR wait_event IS NOT NULL ` +
		`GROUP BY 1,2`

	// run query
	XOLog(sqlstr)
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*GlobalWaitEvents{}
	for q.Next() {
		gwe := GlobalWaitEvents{}

		// scan
		err = q.Scan(&gwe.WaitEventType, &gwe.WaitEvent, &gwe.Count)
		if err != nil {
			return nil, err
		}

		res = append(res, &gwe)
	}

	return res, nil
}
