// This program is copyright 2019-2026 Percona LLC and/or its affiliates.
//
// THIS PROGRAM IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
// WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
//
// This program is free software; you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, version 2.
//
// You should have received a copy of the GNU General Public License, version 2
// along with this program; if not, see <https://www.gnu.org/licenses/>.

// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// PortAndDatadir represents a row from '[custom port_and_datadir]'.
type PortAndDatadir struct {
	Name    string // name
	Setting string // setting
}

// GetPortAndDatadir runs a custom query, returning results as PortAndDatadir.
func GetPortAndDatadir(db XODB) (*PortAndDatadir, error) {
	var err error

	// sql query
	sqlstr := `SELECT name, ` +
		`setting ` +
		`FROM pg_settings ` +
		`WHERE name IN ('port','data_directory')`

	// run query
	XOLog(sqlstr)
	var pad PortAndDatadir
	err = db.QueryRow(sqlstr).Scan(&pad.Name, &pad.Setting)
	if err != nil {
		return nil, err
	}

	return &pad, nil
}
