// This program is copyright 2019-2026 Percona LLC and/or its affiliates.
//
// THIS PROGRAM IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
// WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
//
// This program is free software; you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, version 2.
//
// You should have received a copy of the GNU General Public License, version 2
// along with this program; if not, see <https://www.gnu.org/licenses/>.

// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// ServerVersion represents a row from '[custom server_version]'.
type ServerVersion struct {
	Version string // version
}

// GetServerVersion runs a custom query, returning results as ServerVersion.
func GetServerVersion(db XODB) (*ServerVersion, error) {
	var err error

	// sql query
	const sqlstr = `SELECT current_setting('server_version_num') AS version`

	// run query
	XOLog(sqlstr)
	var sv ServerVersion
	err = db.QueryRow(sqlstr).Scan(&sv.Version)
	if err != nil {
		return nil, err
	}

	return &sv, nil
}
