// This program is copyright 2019-2026 Percona LLC and/or its affiliates.
//
// THIS PROGRAM IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
// WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
//
// This program is free software; you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, version 2.
//
// You should have received a copy of the GNU General Public License, version 2
// along with this program; if not, see <https://www.gnu.org/licenses/>.

// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// Settings
type Setting struct {
	Name    string // name
	Setting string // setting
}

// GetSettings runs a custom query, returning results as Setting.
func GetSettings(db XODB) ([]*Setting, error) {
	var err error

	// sql query
	const sqlstr = `SELECT name, setting ` +
		`FROM pg_settings`

	// run query
	XOLog(sqlstr)
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*Setting{}
	for q.Next() {
		s := Setting{}

		// scan
		err = q.Scan(&s.Name, &s.Setting)
		if err != nil {
			return nil, err
		}

		res = append(res, &s)
	}

	return res, nil
}
