// This program is copyright 2019-2026 Percona LLC and/or its affiliates.
//
// THIS PROGRAM IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
// WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
//
// This program is free software; you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, version 2.
//
// You should have received a copy of the GNU General Public License, version 2
// along with this program; if not, see <https://www.gnu.org/licenses/>.

// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// Tablespaces
type Tablespaces struct {
	Name     Name   // name
	Owner    Name   // owner
	Location string // location
}

// GetTablespaces runs a custom query, returning results as Tablespaces.
func GetTablespaces(db XODB) ([]*Tablespaces, error) {
	var err error

	// sql query
	sqlstr := `SELECT spcname AS Name, ` +
		`pg_catalog.pg_get_userbyid(spcowner) AS Owner, ` +
		`pg_catalog.pg_tablespace_location(oid) AS Location ` +
		`FROM pg_catalog.pg_tablespace ` +
		`ORDER BY 1`

	// run query
	XOLog(sqlstr)
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*Tablespaces{}
	for q.Next() {
		t := Tablespaces{}

		// scan
		err = q.Scan(&t.Name, &t.Owner, &t.Location)
		if err != nil {
			return nil, err
		}

		res = append(res, &t)
	}

	return res, nil
}
