#!/bin/bash
#parse_mysqld_instances

cat <<EOF > $1
  Port  Data Directory             Socket
  ===== ========================== ======
        /var/lib/mysql             /var/lib/mysql/mysql.sock
EOF

cp samples/ps-mysqld-002.txt /tmp/aspersa
