#!/bin/bash

TESTS=4
TMPDIR=$TEST_TMPDIR

cat <<EOF > $TMPDIR/plugins
binlog   ACTIVE   STORAGE ENGINE NULL  GPL
partition   ACTIVE   STORAGE ENGINE NULL  GPL
ARCHIVE  ACTIVE   STORAGE ENGINE NULL  GPL
BLACKHOLE   ACTIVE   STORAGE ENGINE NULL  GPL
CSV   ACTIVE   STORAGE ENGINE NULL  GPL
FEDERATED   DISABLED STORAGE ENGINE NULL  GPL
MEMORY   ACTIVE   STORAGE ENGINE NULL  GPL
InnoDB   ACTIVE   STORAGE ENGINE NULL  GPL
MyISAM   ACTIVE   STORAGE ENGINE NULL  GPL
MRG_MYISAM  ACTIVE   STORAGE ENGINE NULL  GPL
EOF

is \
   "$(get_plugin_status $TMPDIR/plugins InnoDB )"  \
   "ACTIVE"                                  \
   "Sanity test, finds InnoDB as active"

is \
   "$(get_plugin_status $TMPDIR/plugins some_plugin_that_doesnt_exist )"  \
   "Not found"                                  \
   "Doesn't find a nonexistent plugin"

echo "INNODB_CMP  ACTIVE" >> $TMPDIR/plugins
is \
   "$(get_plugin_status $TMPDIR/plugins "INNODB_CMP" )"  \
   "ACTIVE"

cat <<EOF > $TMPDIR/plugins
binlog   ACTIVE   STORAGE ENGINE NULL  GPL
mysql_native_password   ACTIVE   AUTHENTICATION NULL  GPL
mysql_old_password   ACTIVE   AUTHENTICATION NULL  GPL
MRG_MYISAM  ACTIVE   STORAGE ENGINE NULL  GPL
MyISAM   ACTIVE   STORAGE ENGINE NULL  GPL
CSV   ACTIVE   STORAGE ENGINE NULL  GPL
MEMORY   ACTIVE   STORAGE ENGINE NULL  GPL
FEDERATED   DISABLED STORAGE ENGINE NULL  GPL
ARCHIVE  ACTIVE   STORAGE ENGINE NULL  GPL
BLACKHOLE   ACTIVE   STORAGE ENGINE NULL  GPL
InnoDB   ACTIVE   STORAGE ENGINE NULL  GPL
INNODB_TRX  ACTIVE   INFORMATION SCHEMA   NULL  GPL
INNODB_LOCKS   ACTIVE   INFORMATION SCHEMA   NULL  GPL
INNODB_LOCK_WAITS ACTIVE   INFORMATION SCHEMA   NULL  GPL
INNODB_CMP  ACTIVE   INFORMATION SCHEMA   NULL  GPL
INNODB_CMP_RESET  ACTIVE   INFORMATION SCHEMA   NULL  GPL
INNODB_CMPMEM  ACTIVE   INFORMATION SCHEMA   NULL  GPL
INNODB_CMPMEM_RESET  ACTIVE   INFORMATION SCHEMA   NULL  GPL
PERFORMANCE_SCHEMA   ACTIVE   STORAGE ENGINE NULL  GPL
partition   ACTIVE   STORAGE ENGINE NULL  GPL
EOF

is \
   "$(get_plugin_status $TMPDIR/plugins "INNODB_CMP" )"  \
   "ACTIVE"                                              \
   "Doesn't get confused by multiple plugins with the same prefix"
