#!/usr/bin/env perl

use warnings FATAL => 'all';
use English;

# This script checks if all modules necessary for testing Percona Toolkit
# are installed.  It exits 0 if all modules are installed, else it exits
# non-zero.
#
# This check is just for testing Percona Toolkit.  Other dev tasks, like
# building release packages, require other modules and programs.

my @modules = qw(
   Data::Dumper
   DBD::mysql
   DBI
   Digest::MD5
   File::Basename
   File::Find
   File::Spec
   File::Temp
   Getopt::Long
   IO::File
   IO::Uncompress::Inflate
   List::Util
   POSIX
   Socket 
   Test::More
   Time::HiRes
   Time::Local
);

my $exit_status = 0;
my $fmt         = "%-23s %s\n";

# Not a module but we want to know the Perl version.
printf $fmt, "Perl", `perl -v | perl -ne '/v([\\d\\.]+)/ && print \$1'`;

foreach my $module (@modules) {
   my $version = "Not installed";
   eval "require $module";
   if ( $EVAL_ERROR ) { 
      $exit_status = 1;
   }
   else {
      $version = ${"${module}::VERSION"};
   }
   printf $fmt, $module, $version;
}

exit $exit_status;
