#!/bin/bash
#group_by_sample samples/diskstats-001.txt

cat <<EOF > $1
  #ts device    rd_s rd_avkb rd_mb_s rd_mrg rd_cnc   rd_rt    wr_s wr_avkb wr_mb_s wr_mrg wr_cnc   wr_rt busy in_prg
  2.0 {8}      466.5    44.6    10.2     0%    1.4    23.9  1184.0    42.6    24.6    18%    0.0     0.2  12%     18
  4.0 {8}      373.0    47.2     8.6     0%    1.3    27.4   592.0    45.6    13.2    16%    0.0     0.1  11%     17
  5.0 {8}      848.0    42.6    17.7     0%    2.7    25.5  1987.0    49.8    48.3     3%    0.0     0.1  22%      9
  7.0 {8}      340.0    36.6     6.1     0%    1.0    23.8  1149.5    43.4    24.3    23%    0.0     0.2  11%      5
EOF
