#!/usr/bin/env perl

BEGIN {
   die "The PERCONA_TOOLKIT_BRANCH environment variable is not set.\n"
      unless $ENV{PERCONA_TOOLKIT_BRANCH} && -d $ENV{PERCONA_TOOLKIT_BRANCH};
   unshift @INC, "$ENV{PERCONA_TOOLKIT_BRANCH}/lib";
};

use strict;
use warnings FATAL => 'all';
use English qw(-no_match_vars);
use Test::More;

use PerconaTest;
use Sandbox;
require "$trunk/bin/pt-config-diff";

require VersionParser;
my $dp   = new DSNParser(opts=>$dsn_opts);
my $sb   = new Sandbox(basedir => '/tmp', DSNParser => $dp);
my $dbh  = $sb->get_dbh_for('source');

my ($ver, $reset, $set_short, $set_long);

if ( !$dbh ) {
   plan skip_all => 'Cannot connect to sandbox source';
}

if ( $sandbox_version ge '8.0' ) {
   $ver = "80";
   $reset = q{SET GLOBAL tls_ciphersuites = ''};
   $set_short =
      q{SET GLOBAL tls_ciphersuites = '}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256'};
   $set_long =
      q{SET GLOBAL tls_ciphersuites = '}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,}.
      q{TLS_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256'};
}
elsif ( $sandbox_version ge '5.7' ) {
   $ver = "57";
   $reset = q{SET GLOBAL log_syslog_tag = ''};
   $set_short =
      q{SET GLOBAL log_syslog_tag = '}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB'};
   $set_long =
      q{SET GLOBAL log_syslog_tag = '}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}.
      q{B'};
}
else {
   plan skip_all => "Requires MySQL 5.7 or newer";
}

my $output;
my $retval;

$sb->do_as_root('source', $set_short);

$output = output(
   sub { $retval = pt_config_diff::main(
      "${trunk}/t/pt-config-diff/samples/long_vars_${ver}_1.cnf",
      'h=127.1,P=12345,u=msandbox,p=msandbox')
   },
   stderr => 1,
);

is(
   $retval,
   0,
   "No diff on variable value up to 1024 bytes long"
);

$sb->do_as_root('source', $set_long);

$output = output(
   sub { $retval = pt_config_diff::main(
      "${trunk}/t/pt-config-diff/samples/long_vars_${ver}_2.cnf",
      'h=127.1,P=12345,u=msandbox,p=msandbox')
   },
   stderr => 1,
);

is(
   $retval,
   0,
   "No diff on variable value longer than 1024 bytes"
);

# #############################################################################
# Done.
# #############################################################################
$sb->do_as_root('source', $reset);

$sb->wipe_clean($dbh);
ok($sb->ok(), "Sandbox servers") or BAIL_OUT(__FILE__ . " broke the sandbox");
done_testing;