name: libmodulescheck 

on:
  pull_request:
    branches: [ "3.x" ]


jobs:

  libmodulescheck:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4

    - name: run util/check_libmodules_updated 
      run: ./util/check_libmodules_updated
      env:
        INPUT_REF: '${{ github.ref }}'
        INPUT_HEAD_REF: '${{ github.head_ref }}'
